---
autolinks:
  - key_prefix: PREFIX-
    url_template: 'https://tracking-software.com/browse/PREFIX-<num>'
    is_alphanumeric: true

protections:
  - name: main

    # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
    required_pull_request_reviews:

      # Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6
      # or 0 to not require reviewers.
      required_approving_review_count: 1

      # Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.
      dismiss_stale_reviews: true

      # Blocks merging pull requests until code owners review them.
      require_code_owner_reviews: true

      # Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable.
      # User and team dismissal_restrictions are only available to organization-owned repositories.
      # Omit this parameter for personal repositories.
      dismissal_restrictions:
        users: []
        teams: []

      # Whether the most recent push must be approved by someone other than the person who pushes it. Default: false
      require_last_push_approval: true

    # Required. Require status checks to pass before merging. Set to null to disable.
    required_status_checks:

      # Required. Require branches to be up to date before merging.
      strict: true

      # Required. The list of status checks to require in order to merge into this branch.
      contexts: []

    # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status
    # checks for repository administrators. Set to null to disable.
    enforce_admins: true

    # Prevent merge commits from being pushes to matching branches
    required_linear_history: true

    # Require all conversations on code to be resolved before a pull request can be merged into a branch
    # that matches this rule. Set to false to disable. Default: false.
    required_conversation_resolution: true

repository:
  name: RepositoryName

  # A short description of the repository that will show up on GitHub.
  description: This is a repository

  # A URL with more information about the repository.
  homepage: https://github.com/owner/repo

  # Either `true` to enable issues for this repository or `false` to disable them.
  has_issues: false

  # Either `true` to enable projects for this repository or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository or `false` to disable it.
  has_wiki: false

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests or `false` to prevent squash-merging. Default: true
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit or `false` to prevent
  # merging pull requests with a merge commit. Default: true
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests or `false` to prevent rebase-merging. Default: true
  allow_rebase_merge: true

  # Either `true` to allow auto-merge on pull requests, or `false` to disallow auto-merge. Default :false
  allow_auto_merge: true

  # Either `true` to enable automatic deletion of branches on merge or `false` to disable. Default: false
  delete_branch_on_merge: true

  # Either `true` to always allow a pull request head branch that is behind its base branch to be updated
  # even if it is not required to be up to date before merging, or `false` otherwise. Default: false
  allow_update_branch: false

  # Required when using `squash_merge_commit_message`. One of PR_TITLE, COMMIT_OR_PR_TITLE
  squash_merge_commit_title: PR_TITLE

  # The default value for a squash merge commit message. One of PR_BODY, COMMIT_MESSAGES, BLANK
  squash_merge_commit_message: PR_BODY

  # Required when using `merge_commit_message`. One of PR_TITLE, MERGE_MESSAGE
  merge_commit_title: PR_TITLE

  # The default value for a merge commit message. One of PR_TITLE, PR_BODY, BLANK
  merge_commit_message: PR_BODY

  # Either `true` to allow private forks, or `false` to prevent private forks.
  allow_forking: true
